name: main 

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check code format
        uses: axel-op/googlejavaformat-action@v3
        with:
          version: '1.10.0'
          skipCommit: true
          args: '--set-exit-if-changed'

      - name: Prepare test env
        run:  client/script/prepare-test-env.sh

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build and test with Gradle
        run: cd client && ./gradlew build

  build-examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check code format
        uses: axel-op/googlejavaformat-action@v3
        with:
          version: '1.10.0'
          skipCommit: true
          args: '--set-exit-if-changed'

      - name: Prepare env
        run:  examples/start-hstreamdb.sh

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build and run examples
        run: cd examples && ./gradlew build

  embed-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
      - name: Markdown Embed Code From File
        uses: tokusumi/markdown-embed-code@v1.0.0
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "synchronizing readme"
          silent: true
